
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.StartKit.LIB.Bridge;

namespace XTC.FMP.MOD.StartKit.LIB.MVCS
{
    /// <summary>
    /// Healthy的视图桥接层基类（协议部分）
    /// 处理UI的事件
    /// </summary>
    public class HealthyBaseViewBridge : IHealthyViewBridge
    {

        /// <summary>
        /// 直系服务层
        /// </summary>
        public HealthyService? service { get; set; }


        /// <summary>
        /// 处理Echo的提交
        /// </summary>
        /// <param name="_dto">EchoRequest的数据传输对象</param>
        /// <returns>错误</returns>
        public async Task<Error> OnEchoSubmit(IDTO _dto)
        {
            EchoRequestDTO? dto = _dto as EchoRequestDTO;
            if(null == service)
            {
                return Error.NewNullErr("service is null");
            }
            return await service.CallEcho(dto?.message);
        }


    }
}
