
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.StartKit.LIB.Proto;
using XTC.FMP.MOD.StartKit.LIB.Bridge;

namespace XTC.FMP.MOD.StartKit.LIB.MVCS
{

    public class EchoRequestDTO : IDTO
    {
        public EchoRequestDTO(EchoRequest _message)
        {
            message = _message;    
        }
        public readonly EchoRequest message;
    }



    public class EchoResponseDTO : IDTO
    {
        public EchoResponseDTO(EchoResponse _message)
        {
            message = _message;    
        }
        public readonly EchoResponse message;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _message)
        {
            message = _message;    
        }
        public readonly Status message;
    }



}
