
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using Grpc.Core;
using System.Threading.Tasks;
using XTC.FMP.MOD.StartKit.LIB.Proto;

namespace XTC.FMP.MOD.StartKit.App.Service
{
    /// <summary>
    /// Healthy基类
    /// </summary>
    public class HealthyBaseService : Healthy.HealthyBase
    {

        public override Task<EchoResponse> Echo(EchoRequest _request, ServerCallContext _context)
        {
            return Task.FromResult(new EchoResponse
            {
                Status = new LIB.Proto.Status() { Code=-1, Message="Not Implemented"},
            });
        }

    }
}

