//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using Grpc.Core;
using System.Threading.Tasks;
using XTC.FMP.MOD.StartKit.LIB.Proto;

namespace XTC.FMP.MOD.StartKit.LIB.Service
{
    public class HealthyBaseService : Healthy.HealthyBase
    {
        public override Task<EchoResponse> Echo(EchoRequest _request, ServerCallContext _context)
        {
            return Task.FromResult(new EchoResponse
            {
                Status = new Proto.Status() { Code=-1, Message="Not Implemented"},
            });
        }
    }
}
